openapi: 3.0.0
info:
  title: POST - Body Sheet
  version: v1.0.0
servers:
  - url: ''
tags:
  - name: Main
paths:
  '/exec':
    post:
      summary: Get body base info
      tags:
        - Main
      description: Get body base info
      requestBody:
        content:
          text/plain;charset=utf-8:
            schema:
              oneOf:
                - $ref: '#/components/schemas/UserInfoList'
                - $ref: '#/components/schemas/UserInfo'

      responses:
        '200':
          description: base info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BodyComposition'

components:
  schemas:
    UserInfo:
      type: object
      properties:
        birth:
          type: string
          default: '1970-07-22'
        gender:
          type: string
          enum: ['男', '女']
        height:
          type: number
          default: 180
        weight:
          type: number
          default: 65
        lines:
          $ref: '#/components/schemas/Lines'
        skinfolds:
          $ref: '#/components/schemas/Skinfolds'
        bodyFat:
          type: number
          default: 18
        activity:
          type: string
          enum: ['幾乎不動', '輕度', '中度', '重度', '極重度']
        pregnancy:
          type: string
          enum: ['', '第一孕期', '第二孕期', '第三孕期', '哺乳']
      required:
        - birth
        - gender
        - height
        - weight
        - activity
        - pregnancy

    UserInfoList:
      type: array
      items:
        $ref: '#/components/schemas/UserInfo'

    Lines:
      type: object
      properties:
        waistLine:
          type: number
          default: 79
        neckLine:
          type: number
          default: 36
        hipLine:
          type: number
          default: 95

    Skinfolds:
      type: object
      properties:
        abdominal:
          type: number
          default: 16
        thigh:
          type: number
          default: 11
        triceps:
          type: number
          default: 6
        supraspinale:
          type: number
          default: 20

    BodyComposition:
      type: object
      properties:
        dailyCalories:
          type: string
        BMI:
          type: string
        WHtR:
          type: string
        bodyFat:
          $ref: '#/components/schemas/BodyFat'
        BMR:
          $ref: '#/components/schemas/BMR'
        TDEE:
          $ref: '#/components/schemas/TDEE'
        BSA:
          $ref: '#/components/schemas/BSA'

    BodyFat:
      type: object
      properties:
        skinfolds:
          type: string
        lines:
          type: string

    BMR:
      type: object
      properties:
        robertsonAndReidLow:
          type: string
        robertsonAndReidMean:
          type: string
        robertsonAndReidHigh:
          type: string
        revisedHarrisBenedict:
          type: string
        mifflinStJeor:
          type: string
        katchMcArdle:
          type: string
        oxfordEquation:
          type: string

    TDEE:
      type: object
      properties:
        FAO:
          type: string
        redman:
          type: string

    BSA:
      type: object
      properties:
        doubois:
          type: string
        duboisCorrected:
          type: string
        yu:
          type: string
        haycock:
          type: string
        mosteller:
          type: string
