name: deploy gh-pages

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install and Build
        run: |
          yarn
          yarn build
        env:
          REACT_APP_APIKey: ${{ secrets.REACT_APP_GCP_ID }}
          REACT_APP_APISecret: ${{ secrets.REACT_APP_GCP_SECRET }}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.2.0
        with:
          branch: gh-pages
          folder: build
